### ISSUE TITLE
Android Lollipop not working?

### ISSUE THREAD

**Issue by mrtomnguyen** [appcelerator-archive/ti.paint#3] opened 2014-12-09 01:10 UTC
has anyone tested the Android module on Lollipop yet? 

It's not working for me.

**Comment by mitulbhalia** [comment] 2016-02-05 06:04
Yes, for me its not working....

**Comment by ashcoding** [comment] 2016-02-05 06:07
Have you tried https://github.com/appcelerator-modules/ti.paint/releases/tag/android-2.0.3 ?

**Comment by mitulbhalia** [comment] 2016-02-05 06:10
@ashcoding yes, Just tried yesterday....but its not working properly.

**Comment by ashcoding** [comment] 2016-02-05 06:14
Could you provide more information, logs and any other info such as Android version?
Eg, the code to reproduce, what version of android, etc...

**Comment by mitulbhalia** [comment] 2016-02-05 06:19
@ashcoding I am testing it on Android version 5.0.2
Device : ASUS ZENFONE LASER 2

I am setting strokeWidth and strokeAlpha using slider but its does not set properly. It accepts the value but it draws nothing after setting these properties.

**Comment by mitulbhalia** [comment] 2016-02-08 06:49
@ashcoding Any solution?

**Comment by mitulbhalia** [comment] 2016-03-03 05:54
@ashcoding May I know the reason why its not working properly or may be you have workaround.

**Comment by ashcoding** [comment] 2016-03-03 06:38
Hi, to move this issue forward, it's best to create a JIRA ticket rather then having it here as a Github issue. Information is provided here http://docs.appcelerator.com/platform/latest/#!/guide/How_to_Submit_a_Bug_Report 

I recommend it to be created as a TIMOB or AC (Appcelerator Community) Ticket.

**Comment by hansemannn** [comment] 2016-08-20 19:55
The `strokeWidth` issue was fixed in the latest 2.0.4 version.

**Closed by hansemannn** 2016-08-20 19:55 UTC
